version: '3.9'

services:
  mongodb:
    container_name: mongo.db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/var/lib/monogodb/data
    networks:
      - blazor_exam
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin@123$$

  sqlserver:
    container_name: mssql.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/lib/sqlserver/data
    networks:
      - blazor_exam
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123$$

networks:
  blazor_exam:
    driver: bridge
volumes:
  mongo-data:
  mssql-data: